name: CI

permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DUMMY_ENV: "Environment Variable Exists"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: |
          echo "Checking Environment Variable..."
          echo "DUMMY_ENV = $DUMMY_ENV"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      - name: Set MLflow Tracking URI
        run: |
          export MLFLOW_TRACKING_URI="file:./mlruns"
          echo "MLflow Tracking URI set to local folder"

      - name: Run mlflow project
        run: |
          mlflow run MLProject --env-manager=local
        
      - name: Install Python dependencies
        run: |
          if [ -f "MLProject/requirements.txt" ]; then
            pip install -r MLProject/requirements.txt
          else
            echo "Tidak ada requirements.txt"
          fi

      - name: Upload to Github LFS
        run: |
          git config --global user.name ${{ secrets.username }}
          git config --global user.email ${{ secrets.email }}
          git lfs track "mlruns/**"
          git add .gitattributes
          git add -f mlruns/
          git commit -m "Upload mlruns output from CI" || true
          git push origin main
